package gestionpharmacie;

import java.sql.*;
import com.mysql.jdbc.PreparedStatement;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author djira
 */
public class Inscription extends javax.swing.JFrame {
    Statement stmt;
    ResultSet rs ;
    connexionToDatabase connexion = new connexionToDatabase();
    PreparedStatement pst=null;

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
    }
       public static boolean verifierPseudo(String p )
            {
                        connexionToDatabase connexion = new connexionToDatabase();
                        Statement stm;
                        String donnee; ResultSet rs;
                        boolean  possible = false;
                        try
                        {
                           stm = connexion.getConnexionFromDatabase().createStatement();
                           donnee ="SELECT * FROM pharmacies ";
                            rs=stm.executeQuery(donnee);
                            while (rs.next()){
                               if(p.equals(rs.getString("pseudo"))){
                                   possible=false;
                               }else
                               {
                                   possible=true;
                               }
                            }                      
                        }catch(SQLException ex){
                            System.err.println(ex);              
                        }
                       return possible;
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        localite = new javax.swing.JTextField();
        villa = new javax.swing.JTextField();
        pseudo = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        pwd2 = new javax.swing.JPasswordField();
        pwd1 = new javax.swing.JPasswordField();
        boutonIns = new javax.swing.JLabel();
        bouttonRetour = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 40, 30));

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 30, 30));

        contact.setBackground(new java.awt.Color(255, 255, 255));
        contact.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(153, 153, 153));
        contact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contact.setBorder(null);
        contact.setOpaque(false);
        contact.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 517, 300, 40));

        localite.setBackground(new java.awt.Color(255, 255, 255));
        localite.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        localite.setForeground(new java.awt.Color(153, 153, 153));
        localite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        localite.setBorder(null);
        localite.setOpaque(false);
        localite.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(localite, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 408, 300, 40));

        villa.setBackground(new java.awt.Color(255, 255, 255));
        villa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        villa.setForeground(new java.awt.Color(153, 153, 153));
        villa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        villa.setBorder(null);
        villa.setOpaque(false);
        villa.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(villa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 300, 40));

        pseudo.setBackground(new java.awt.Color(255, 255, 255));
        pseudo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pseudo.setForeground(new java.awt.Color(153, 153, 153));
        pseudo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pseudo.setBorder(null);
        pseudo.setOpaque(false);
        pseudo.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 239, 300, 40));

        nom.setBackground(new java.awt.Color(255, 255, 255));
        nom.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        nom.setForeground(new java.awt.Color(153, 153, 153));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setBorder(null);
        nom.setOpaque(false);
        nom.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        nom.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 184, 300, 40));

        pwd2.setBackground(new java.awt.Color(255, 255, 255));
        pwd2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pwd2.setForeground(new java.awt.Color(153, 153, 153));
        pwd2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwd2.setBorder(null);
        pwd2.setOpaque(false);
        pwd2.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 300, 40));

        pwd1.setBackground(new java.awt.Color(255, 255, 255));
        pwd1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        pwd1.setForeground(new java.awt.Color(153, 153, 153));
        pwd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pwd1.setBorder(null);
        pwd1.setOpaque(false);
        pwd1.setSelectionColor(new java.awt.Color(204, 255, 255));
        getContentPane().add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 294, 300, 40));

        boutonIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/ins.png"))); // NOI18N
        boutonIns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonInsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boutonInsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boutonInsMouseExited(evt);
            }
        });
        getContentPane().add(boutonIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, -1, 40));

        bouttonRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/retour.png"))); // NOI18N
        bouttonRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouttonRetourMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bouttonRetourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bouttonRetourMouseExited(evt);
            }
        });
        getContentPane().add(bouttonRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, 200, 40));

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/fondIns.png"))); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonInsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonInsMouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("insH.png"));
        boutonIns.setIcon(img);
    }//GEN-LAST:event_boutonInsMouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
                // TODO add your handling code here:
                System.exit(0);
                
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(Inscription.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void boutonInsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonInsMouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("ins.png"));
        boutonIns.setIcon(img);
    }//GEN-LAST:event_boutonInsMouseExited

    private void bouttonRetourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonRetourMouseEntered
        // TODO add your handling code here:
         ImageIcon img = new ImageIcon(getClass().getResource("retourH.png"));
        bouttonRetour.setIcon(img);
    }//GEN-LAST:event_bouttonRetourMouseEntered

    private void bouttonRetourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonRetourMouseExited
        // TODO add your handling code here:
         ImageIcon img = new ImageIcon(getClass().getResource("retour.png"));
        bouttonRetour.setIcon(img);
    }//GEN-LAST:event_bouttonRetourMouseExited

    private void bouttonRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonRetourMouseClicked
        // TODO add your handling code here:
         dispose();
        new MaPharmacie().setVisible(true);
    }//GEN-LAST:event_bouttonRetourMouseClicked

    private void boutonInsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonInsMouseClicked
        // TODO add your handling code here:
        String nomP=nom.getText();
        String pseudoP=pseudo.getText();
        String pwd1P=pwd1.getText();
        String pwd2P=pwd2.getText();
        String localiteP=localite.getText();
        String adresseP=villa.getText();
        String contactP=contact.getText();
        
        String requete="INSERT INTO pharmacies(nomPharm,pseudo,motdepasse,localite,adresse,contact)"
                + "VALUE('"+nomP+"','"+pseudoP+ "','"+pwd1P+"','"+localiteP+"','"+adresseP+"','"+contactP+"')";
         boolean notexist= verifierPseudo(pseudoP );
            try{

               if(notexist==true){
                            if(pwd1P.equals(pwd2P)){
                                 stmt=connexion.getConnexionFromDatabase().createStatement();
                                 stmt.executeUpdate(requete);
                                 JOptionPane.showMessageDialog(null, "Vous etes inscris avec succès !");
                            }else{
                                 JOptionPane.showMessageDialog(null, "Vos mots de passe ne correspondent pas !");   
                            }
                        }else{
                       JOptionPane.showMessageDialog(null, "pseudo déjà utilisé !");
                        }                    
                }catch(SQLException ex){
                System.err.println(ex);
           }
        
        
    }//GEN-LAST:event_boutonInsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boutonIns;
    private javax.swing.JLabel bouttonRetour;
    private javax.swing.JTextField contact;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField localite;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pseudo;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JTextField villa;
    // End of variables declaration//GEN-END:variables
}
