/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionpharmacie;

import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author djira
 */

public class MaPharmacie extends javax.swing.JFrame {
    Statement stmt;
    ResultSet rs ;
    connexionToDatabase connexion = new connexionToDatabase();

    /**
     * Creates new form MaPharmacie
     */
    public MaPharmacie() {
        initComponents();
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
        panelStock.setVisible(false);
        panelConsulterVente.setVisible(false);
        panelAccueil.setVisible(false);
        jPanel1.setVisible(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelConnexion = new javax.swing.JPanel();
        textPseudo = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        bconn = new javax.swing.JLabel();
        binscription = new javax.swing.JLabel();
        bConnexion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelPwd = new javax.swing.JLabel();
        labelNom = new javax.swing.JLabel();
        labelPseudo = new javax.swing.JLabel();
        deconnexion = new javax.swing.JLabel();
        reglage = new javax.swing.JLabel();
        entete = new javax.swing.JLabel();
        panelAlerte = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bouttonVente = new javax.swing.JButton();
        bouttonAppro = new javax.swing.JButton();
        bouttonStock = new javax.swing.JButton();
        bouttonStat = new javax.swing.JButton();
        bouttonParam = new javax.swing.JButton();
        bureau = new javax.swing.JDesktopPane();
        panelVente = new javax.swing.JPanel();
        comboTypeVente = new javax.swing.JComboBox<>();
        textQuantiteVente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bEnregistrerVente = new javax.swing.JButton();
        textLibelleVente = new javax.swing.JTextField();
        textPrixVente = new javax.swing.JTextField();
        bAnnulerVente = new javax.swing.JButton();
        panelAppro = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bEnregistrerAppro = new javax.swing.JButton();
        bAnnulerAppro = new javax.swing.JButton();
        comboTypeAppro = new javax.swing.JComboBox<>();
        textLibelleAppro = new javax.swing.JTextField();
        textPrixAppro = new javax.swing.JTextField();
        textQuantiteAppro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        textannee = new javax.swing.JTextField();
        textreference = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        panelConsulterVente = new javax.swing.JPanel();
        comboTypeMedic = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        boutonOk1 = new javax.swing.JButton();
        panelStock = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        boutonOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelAccueil = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        textRecherche = new javax.swing.JTextField();
        btnReach = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        comboTypeR = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 720));
        setSize(new java.awt.Dimension(1366, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textPseudo.setBackground(new java.awt.Color(245, 247, 246));
        textPseudo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textPseudo.setForeground(new java.awt.Color(153, 153, 153));
        textPseudo.setBorder(null);
        textPseudo.setOpaque(false);

        textPassword.setBackground(new java.awt.Color(245, 247, 246));
        textPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textPassword.setForeground(new java.awt.Color(153, 153, 153));
        textPassword.setBorder(null);
        textPassword.setOpaque(false);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/connexionH.png"))); // NOI18N

        bconn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/seConn.png"))); // NOI18N
        bconn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bconnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bconnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bconnMouseExited(evt);
            }
        });

        binscription.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/bIns.png"))); // NOI18N
        binscription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binscriptionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                binscriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                binscriptionMouseExited(evt);
            }
        });

        bConnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueilcon.png"))); // NOI18N

        javax.swing.GroupLayout panelConnexionLayout = new javax.swing.GroupLayout(panelConnexion);
        panelConnexion.setLayout(panelConnexionLayout);
        panelConnexionLayout.setHorizontalGroup(
            panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(460, 460, 460)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(bconn))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(textPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(704, 704, 704)
                .addComponent(binscription, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bConnexion)
        );
        panelConnexionLayout.setVerticalGroup(
            panelConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel14)
                .addGap(340, 340, 340)
                .addComponent(bconn))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(textPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(binscription))
            .addGroup(panelConnexionLayout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bConnexion)
        );

        getContentPane().add(panelConnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 720));

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        labelPwd.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        labelPwd.setForeground(new java.awt.Color(255, 255, 255));
        labelPwd.setText("jLabel16");
        getContentPane().add(labelPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 95, 60, 30));

        labelNom.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        labelNom.setForeground(new java.awt.Color(255, 255, 255));
        labelNom.setText("jLabel16");
        getContentPane().add(labelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 64, 60, 30));

        labelPseudo.setFont(new java.awt.Font("Gill Sans MT Ext Condensed Bold", 0, 24)); // NOI18N
        labelPseudo.setForeground(new java.awt.Color(255, 255, 255));
        labelPseudo.setText("jLabel16");
        getContentPane().add(labelPseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 95, 60, 30));

        deconnexion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        deconnexion.setForeground(new java.awt.Color(102, 102, 102));
        deconnexion.setText("  se déconnecter  ");
        deconnexion.setBorder(new javax.swing.border.MatteBorder(null));
        deconnexion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexionMouseClicked(evt);
            }
        });
        getContentPane().add(deconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 70, -1, -1));

        reglage.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        reglage.setForeground(new java.awt.Color(102, 102, 102));
        reglage.setText("       paramètres  ");
        reglage.setBorder(new javax.swing.border.MatteBorder(null));
        reglage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(reglage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 100, 118, -1));

        entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/entete.png"))); // NOI18N
        getContentPane().add(entete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 150));

        panelAlerte.setBackground(new java.awt.Color(255, 255, 255));
        panelAlerte.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rubrique Alerte", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 153, 153))); // NOI18N
        panelAlerte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Libellé", "Expire dans : (jrs)"
            }
        ));
        jTable3.setRowHeight(25);
        jScrollPane3.setViewportView(jTable3);

        panelAlerte.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 190));

        jTable4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Libellé", "Restant"
            }
        ));
        jTable4.setRowHeight(25);
        jScrollPane4.setViewportView(jTable4);

        panelAlerte.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 180));

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Médicaments qui ont atteint ");
        panelAlerte.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Médicaments qui vont bientot expirer");
        panelAlerte.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("le seuil d'approvisionnement");
        panelAlerte.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        getContentPane().add(panelAlerte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 570));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bouttonVente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/vente0.png"))); // NOI18N
        bouttonVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouttonVenteMouseClicked(evt);
            }
        });
        bouttonVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonVenteActionPerformed(evt);
            }
        });
        jPanel1.add(bouttonVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 160, 100));

        bouttonAppro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/appro0.png"))); // NOI18N
        bouttonAppro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bouttonApproMouseClicked(evt);
            }
        });
        bouttonAppro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonApproActionPerformed(evt);
            }
        });
        jPanel1.add(bouttonAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 160, 100));

        bouttonStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/stock0.png"))); // NOI18N
        bouttonStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonStockActionPerformed(evt);
            }
        });
        jPanel1.add(bouttonStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 160, 100));

        bouttonStat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/consultVente.png"))); // NOI18N
        bouttonStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonStatActionPerformed(evt);
            }
        });
        jPanel1.add(bouttonStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 160, 100));

        bouttonParam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionpharmacie/aa.png"))); // NOI18N
        bouttonParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonParamActionPerformed(evt);
            }
        });
        jPanel1.add(bouttonParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 160, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, 570));

        bureau.setBackground(new java.awt.Color(255, 255, 255));
        bureau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVente.setBackground(new java.awt.Color(255, 255, 255));
        panelVente.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(119, 211, 170)));
        panelVente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboTypeVente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aliment", "comprime", "gamme", "presticide", "sirop", "autres" }));
        panelVente.add(comboTypeVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 131, 198, 39));
        panelVente.add(textQuantiteVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 206, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/entetevente.png"))); // NOI18N
        panelVente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setForeground(new java.awt.Color(119, 211, 170));
        jLabel2.setText("Type de médicamment");
        panelVente.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 131, -1, 39));

        jLabel3.setForeground(new java.awt.Color(119, 211, 170));
        jLabel3.setText("Libellé");
        panelVente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 142, -1, -1));

        jLabel4.setForeground(new java.awt.Color(119, 211, 170));
        jLabel4.setText("Prix");
        panelVente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 188, -1, 37));

        jLabel5.setForeground(new java.awt.Color(119, 211, 170));
        jLabel5.setText("Guantité");
        panelVente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 188, 79, 37));

        bEnregistrerVente.setForeground(new java.awt.Color(119, 211, 170));
        bEnregistrerVente.setText("enregistrer");
        bEnregistrerVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEnregistrerVenteMouseClicked(evt);
            }
        });
        bEnregistrerVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnregistrerVenteActionPerformed(evt);
            }
        });
        panelVente.add(bEnregistrerVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 253, 100, -1));
        panelVente.add(textLibelleVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 131, 206, 39));
        panelVente.add(textPrixVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 187, 206, 39));

        bAnnulerVente.setForeground(new java.awt.Color(119, 211, 170));
        bAnnulerVente.setText("annuler");
        bAnnulerVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAnnulerVenteMouseClicked(evt);
            }
        });
        panelVente.add(bAnnulerVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 253, 100, -1));

        bureau.add(panelVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 330));

        panelAppro.setBackground(new java.awt.Color(255, 255, 255));
        panelAppro.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(119, 211, 170)));
        panelAppro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app.png"))); // NOI18N
        panelAppro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel7.setForeground(new java.awt.Color(119, 211, 170));
        jLabel7.setText("Type de médicamment");
        panelAppro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 137, -1, -1));

        jLabel8.setForeground(new java.awt.Color(119, 211, 170));
        jLabel8.setText("référence ");
        panelAppro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel9.setForeground(new java.awt.Color(119, 211, 170));
        jLabel9.setText("Prix");
        panelAppro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, 37));

        jLabel10.setForeground(new java.awt.Color(119, 211, 170));
        jLabel10.setText("Guantité");
        panelAppro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 181, 79, 37));

        bEnregistrerAppro.setText("enregistrer");
        bEnregistrerAppro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnregistrerApproActionPerformed(evt);
            }
        });
        panelAppro.add(bEnregistrerAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 100, -1));

        bAnnulerAppro.setText("annuler");
        bAnnulerAppro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bAnnulerApproMouseClicked(evt);
            }
        });
        panelAppro.add(bAnnulerAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 100, -1));

        comboTypeAppro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aliment", "comprime", "gamme", "presticide", "sirop", "autres" }));
        panelAppro.add(comboTypeAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 122, 198, 39));
        panelAppro.add(textLibelleAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 210, 39));
        panelAppro.add(textPrixAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 210, 39));
        panelAppro.add(textQuantiteAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 180, 199, 39));

        jLabel11.setForeground(new java.awt.Color(119, 211, 170));
        jLabel11.setText("Date d'expiration (année/moi/jour) : ");
        panelAppro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 37));

        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox2MouseExited(evt);
            }
        });
        panelAppro.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 60, -1));

        panelAppro.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 60, -1));
        panelAppro.add(textannee, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 80, -1));
        panelAppro.add(textreference, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 210, 39));

        jLabel17.setForeground(new java.awt.Color(119, 211, 170));
        jLabel17.setText("Libellé");
        panelAppro.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 137, -1, -1));

        bureau.add(panelAppro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 450));

        panelConsulterVente.setBackground(new java.awt.Color(255, 255, 255));
        panelConsulterVente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulter les ventes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(119, 211, 170))); // NOI18N
        panelConsulterVente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboTypeMedic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aliment", "comprime", "gamme", "presticide", "sirop", "autres" }));
        panelConsulterVente.add(comboTypeMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 153, -1));

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Type de médicamment");
        panelConsulterVente.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, -1));

        jTable2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom ", "Quantite", "Prix", "Date Vente"
            }
        ));
        jTable2.setRowHeight(30);
        jScrollPane2.setViewportView(jTable2);

        panelConsulterVente.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 664, 310));

        boutonOk1.setText("ok");
        boutonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOk1ActionPerformed(evt);
            }
        });
        panelConsulterVente.add(boutonOk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 142, -1));

        bureau.add(panelConsulterVente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 430));

        panelStock.setBackground(new java.awt.Color(255, 255, 255));
        panelStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulter Stock", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 0, 24), new java.awt.Color(119, 211, 170))); // NOI18N
        panelStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aliment", "comprime", "gamme", "presticide", "sirop", "autres" }));
        panelStock.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 153, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Type de médicamment");
        panelStock.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 140, -1));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom ", "Référence", "Prix", "Date appro", "Date d'expiration", "Quantité restante"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        panelStock.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 664, 300));

        boutonOk.setText("ok");
        boutonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOkActionPerformed(evt);
            }
        });
        panelStock.add(boutonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 142, -1));

        jButton2.setText("rechercher ");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        panelStock.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        bureau.add(panelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 410));

        panelAccueil.setBackground(new java.awt.Color(255, 255, 255));
        panelAccueil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "\nACCUEIL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium Cond", 1, 24), new java.awt.Color(119, 211, 170))); // NOI18N
        panelAccueil.setForeground(new java.awt.Color(255, 255, 255));
        panelAccueil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setForeground(new java.awt.Color(119, 211, 170));
        jLabel22.setText("Rechercher");
        panelAccueil.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 100, 20));
        panelAccueil.add(textRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 160, -1));

        btnReach.setText("  rechercher  ");
        btnReach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReachActionPerformed(evt);
            }
        });
        panelAccueil.add(btnReach, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 200, -1));

        jTable5.setBackground(new java.awt.Color(255, 255, 255));
        jTable5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Prix"
            }
        ));
        jTable5.setGridColor(new java.awt.Color(204, 204, 204));
        jTable5.setRowHeight(25);
        jTable5.setRowMargin(5);
        jScrollPane5.setViewportView(jTable5);

        panelAccueil.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 660, 270));

        comboTypeR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aliment", "comprime", "gamme", "presticide", "sirop", "autres" }));
        panelAccueil.add(comboTypeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 150, -1));

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelAccueil.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 210, -1));

        bureau.add(panelAccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 950, 560));

        getContentPane().add(bureau, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 980, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonVenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouttonVenteActionPerformed

    private void bAnnulerApproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnnulerApproMouseClicked
        // TODO add your handling code here:
        panelAppro.setVisible(false);
    }//GEN-LAST:event_bAnnulerApproMouseClicked

    private void bouttonVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonVenteMouseClicked
        // TODO add your handling code here:
        panelVente.setVisible(true);
        panelAppro.setVisible(false);
        panelStock.setVisible(false);
         panelConsulterVente.setVisible(false);
         panelAccueil.setVisible(false);
    }//GEN-LAST:event_bouttonVenteMouseClicked

    private void bouttonApproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bouttonApproMouseClicked
        // TODO add your handling code here:
        for (int i = 1; i <= 12; i++) {
            if (i<10) {
                jComboBox2.addItem("0"+i+"");
            }else{
                jComboBox2.addItem(""+i+"");
            }
            
        }
        for (int i = 1; i <= 31; i++) {
                if (i < 10) {
                    jComboBox4.addItem("0"+i+"");
                }else{
                    jComboBox4.addItem(""+i+"");

                }
        }
        
        panelAppro.setVisible(true);
        panelVente.setVisible(false);
        panelStock.setVisible(false);
         panelConsulterVente.setVisible(false);
         panelAccueil.setVisible(false);
         

    }//GEN-LAST:event_bouttonApproMouseClicked

    private void bAnnulerVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAnnulerVenteMouseClicked
        // TODO add your handling code here:
        panelVente.setVisible(false);
    }//GEN-LAST:event_bAnnulerVenteMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
       System.exit(0); 
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
       this.setState(MaPharmacie.ICONIFIED);
         
    }//GEN-LAST:event_jLabel13MouseClicked

    private void bconnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bconnMouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("seConnH.png"));
        bconn.setIcon(img);
    }//GEN-LAST:event_bconnMouseEntered

    private void binscriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binscriptionMouseEntered
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("binsHover.png"));
        binscription.setIcon(img);
    }//GEN-LAST:event_binscriptionMouseEntered

    private void bconnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bconnMouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("seConn.png"));
        bconn.setIcon(img);
    }//GEN-LAST:event_bconnMouseExited

    private void binscriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binscriptionMouseExited
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon(getClass().getResource("bIns.png"));
        binscription.setIcon(img);
    }//GEN-LAST:event_binscriptionMouseExited

    private void bconnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bconnMouseClicked

        boolean a=false;
        if(textPseudo.getText().equals("") || textPassword.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Remplissez tous les champs SVP !");
            }        
        else
        {
            String info= "select * from pharmacies where pseudo= '"+textPseudo.getText()+"' ";  
            
          try{
            stmt = connexion.getConnexionFromDatabase().createStatement();          
            rs=stmt.executeQuery(info);
                       
            if(rs.next()){                                        
                    panelConnexion.setVisible(false);
                    jPanel1.setVisible(true);
                    a=true;
                    labelNom.setText(rs.getString("nomPharm"));
                    labelPseudo.setText(rs.getString("pseudo"));
                    labelPwd.setText(rs.getString("motdepasse"));
                    textPseudo.setText("");
                    textPassword.setText("");
                    
            }else{
                JOptionPane.showMessageDialog(null, "Mot de passe ou pseudo incorrect !");
            }
       
        }catch(SQLException ex)
        {
            System.err.println(ex);
        }finally{
            try {
//                rs.close();
                  stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(MaPharmacie.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
     }
        if(a==true){
            //String pesticides="presticide";
             //String comp="comprime";
            String stock="stock";
           // fonctions.AlerteExpiration(pesticides,jTable3);
            fonctions.AlerteExpiration(stock,jTable3,labelPseudo.getText());
            fonctions.AlerteAppro(stock,jTable4,labelPseudo.getText());
            fonctions.Recherche( "stock", jTable5, textRecherche.getText(),comboTypeR.getSelectedItem().toString(),labelPseudo.getText() );
        }
        
    }//GEN-LAST:event_bconnMouseClicked

    private void binscriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binscriptionMouseClicked
        // TODO add your handling code here:
         dispose();
        new Inscription().setVisible(true);
    }//GEN-LAST:event_binscriptionMouseClicked

    private void bouttonStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonStockActionPerformed
        // TODO add your handling code here:
       Statement stmt;
    ResultSet rs ;
    connexionToDatabase connexion = new connexionToDatabase();
    PreparedStatement pst=null;
        panelStock.setVisible(true);
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
        panelAccueil.setVisible(false);
         panelConsulterVente.setVisible(false);
         String identifiant = labelPseudo.getText ();  
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" type");
        model.addColumn(" nom");
        model.addColumn("Quantite");
      
         String sql="select * from stock where idphar='"+identifiant+"'";
         try
       {
         
        
         stmt=connexion.getConnexionFromDatabase().createStatement();
          ResultSet resultat = stmt.executeQuery(sql); 
            while (resultat.next()){
         model.addRow(new Object[]{resultat.getString("type"),resultat.getString("nom"),resultat.getString("quantite")});
             }
        }
       catch(SQLException ex) {
            System.err.println(ex);
           
       }
           jTable1.setModel(model);
    }//GEN-LAST:event_bouttonStockActionPerformed

    private void boutonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOkActionPerformed
        // TODO add your handling code here:
        panelStock.setVisible(false);
    }//GEN-LAST:event_boutonOkActionPerformed

    private void deconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexionMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "A bientot !");
        jPanel1.setVisible(false);
        panelConnexion.setVisible(true);
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
        panelStock.setVisible(false);
        panelAccueil.setVisible(false);
        panelConsulterVente.setVisible(false);
    }//GEN-LAST:event_deconnexionMouseClicked

    private void boutonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOk1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel modeltable = new DefaultTableModel();
         
        modeltable.addColumn("Libelle");
        modeltable.addColumn("Quantite");
        modeltable.addColumn("Prix");
         modeltable.addColumn("Date Vente");
        
        String req1="select * from Vente where idphar='"+labelPseudo.getText()+"' AND typeMedoc='"+comboTypeMedic.getSelectedItem().toString()+"'";
         try{
		stmt=connexion.getConnexionFromDatabase().createStatement();
	          ResultSet rs = stmt.executeQuery(req1);
        	  while (rs .next()){
             	modeltable.addRow(new Object[]{rs .getString("Libelle"), rs.getString("Quantite"),rs.getString("Prix"),rs.getString("datevente")});
    }
         }
catch(SQLException ex){
    System.out.println(ex);
}
         jTable2.setModel(modeltable);
    }//GEN-LAST:event_boutonOk1ActionPerformed

    private void bouttonStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonStatActionPerformed
        // TODO add your handling code here:
        panelConsulterVente.setVisible(true);
        panelStock.setVisible(false);
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
        panelAccueil.setVisible(false);
    }//GEN-LAST:event_bouttonStatActionPerformed

    private void btnReachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReachActionPerformed

        if(!textRecherche.getText().equals("")){
        fonctions.Recherche( "stock", jTable5, textRecherche.getText(),comboTypeR.getSelectedItem().toString(),labelPseudo.getText() );
        }else{
            JOptionPane.showMessageDialog(null, "Donnez le libellé du médicaments ");
        }
    }//GEN-LAST:event_btnReachActionPerformed

    private void bouttonParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonParamActionPerformed
        // TODO add your handling code here:
        panelAccueil.setVisible(true);
        panelConsulterVente.setVisible(false);
        panelStock.setVisible(false);
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
    }//GEN-LAST:event_bouttonParamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelAccueil.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bEnregistrerApproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnregistrerApproActionPerformed
        // TODO add your handling code here:
        Statement smt0,smt88,mnt1,smt,stat1,mnt;
        ResultSet rs0,rs88;
        int var = 0;
        String nom = textLibelleAppro.getText ();  
        String quantite = textQuantiteAppro.getText ();
        String identifiant = labelPseudo.getText ();
        String prix = textPrixAppro.getText ();
      String sql="select * from stock where idphar='"+identifiant+"' AND nom='"+nom+"' ";
      
      int newquant= 0;
      try{
           smt0=connexion.getConnexionFromDatabase().createStatement();
           rs0=smt0.executeQuery(sql);
            if(rs0.next()){
               String qt=rs0.getString("quantite");
               newquant=Integer.valueOf(qt)+Integer.valueOf(quantite);
               JOptionPane.showMessageDialog(null,newquant);
            
            }
            
        }
        catch (Exception ex){
            System.err.println(ex);
           // JOptionPane.showMessageDialog(null, "non");
        } 
   
      String sql1="select * from stock where idphar='"+identifiant+"' AND nom='"+nom+"' ";
      
      int newquant1= 0;
      try{
           smt88=connexion.getConnexionFromDatabase().createStatement();
           rs88=smt88.executeQuery(sql);
            while(rs88.next()){
               var++;
            
            }
        }
        catch (Exception ex){
            System.err.println(ex);
           // JOptionPane.showMessageDialog(null, "non");
        } 
      
      
   String dat=textannee.getText().toString()+"-"+jComboBox2.getSelectedItem().toString()+"-"+jComboBox4.getSelectedItem().toString();
   String reference=textreference.getText();
  String Box=comboTypeAppro.getSelectedItem().toString();
          
    String requete = "INSERT INTO "+Box+" (idphar,nom,quantite,prix,dateexpiration ) VALUES ('"+nom+"','"+quantite+"','"+prix+"','"+dat+"')" ;
    if (var==0){
    String requete1 = "INSERT INTO stock (idphar,type ,nom,reference,prix, quantite,dateexpiration ) VALUES ('"+identifiant+"','"+Box+"','"+nom+"','"+reference+"','"+prix+"','"+quantite+"','"+dat+"')" ;// TODO add your handling code here:
   
     try
       {
         
          mnt1=connexion.getConnexionFromDatabase().createStatement();
       mnt1.executeUpdate(requete1);
        
   
           JOptionPane.showMessageDialog(null,"Approvisionnement enregistre avec succes");
       }
       catch(SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(null,"Impossible d'enregistrer");  
       }
    }
    else {
        String requete2 = "UPDATE stock SET quantite= '"+newquant+"' WHERE idphar='"+identifiant+"' AND nom='"+nom+"' ";
     try
       {
         smt=connexion.getConnexionFromDatabase().createStatement();
         smt.executeUpdate(requete);
          mnt=connexion.getConnexionFromDatabase().createStatement();
       //  mnt.executeUpdate(requete1);
        
         stat1=connexion.getConnexionFromDatabase().createStatement();
         stat1.executeUpdate(requete2);
           JOptionPane.showMessageDialog(null,"Approvisionnement enregistre avec succes");
       }
       catch(SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(null,"Impossible d'enregistrer");  
       }
    }
    }//GEN-LAST:event_bEnregistrerApproActionPerformed

    private void bEnregistrerVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnregistrerVenteActionPerformed
        // TODO add your handling code here:
        DateFormat fd = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date aujourdhui = Calendar.getInstance().getTime();
	String dateFormatee = fd.format(aujourdhui);
        String TypeMedoc;
         String dat=dateFormatee;
        TypeMedoc = comboTypeVente.getSelectedItem().toString();
	String NomMedoc = textLibelleVente.getText();
        int Quantite = Integer.valueOf(textQuantiteVente.getText());
	int Prix = Integer.valueOf(textPrixVente.getText());

  
        String requete="INSERT INTO Vente (idphar,typeMedoc,libelle,quantite,prix,datevente) VALUES('"+labelPseudo.getText()+"','"+TypeMedoc+"','"+NomMedoc+"','"+Quantite+"','"+Prix+"','"+dat+"')";
      
 
       Statement smt0,smt88,mnt1,smt,stat1,mnt;
        ResultSet rs0,rs88;
        int var = 0;
        String nom = textLibelleVente.getText ();  
       String quantite = textQuantiteVente.getText ();
      String identifiant = labelPseudo.getText ();
   
      String sql="select * from stock where idphar='"+identifiant+"' AND nom='"+nom+"' ";
      
      int newquant= 0;
     
   
     try{
           smt88=connexion.getConnexionFromDatabase().createStatement();
           rs88=smt88.executeQuery(sql);
            while(rs88.next()){
               var++;
               if(var==1){
                   newquant=Integer.valueOf(rs88.getString("quantite"))-Quantite;
                    try{
                        stmt=connexion.getConnexionFromDatabase().createStatement();
                        stmt.executeUpdate(requete);
                        JOptionPane.showMessageDialog(null,"Vente enregistrée avec succes");
                        panelVente.setVisible(false);
                         }                                        
                      catch(SQLException ex){
                         System.out.println(ex);
                     }
                    
                    String requete2 = "UPDATE stock SET quantite= '"+newquant+"' WHERE idphar='"+identifiant+"' AND nom='"+nom+"' ";
                    try
                      {
                        stat1=connexion.getConnexionFromDatabase().createStatement();
                        stat1.executeUpdate(requete2);
                      }
                      catch(SQLException ex) {
                           System.err.println(ex); 
                      }
                    break;
            }
            
            }
            
        }
        catch (Exception ex){
            System.err.println(ex);
            JOptionPane.showMessageDialog(null, "non");
        } 
      
    }//GEN-LAST:event_bEnregistrerVenteActionPerformed

    private void bouttonApproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonApproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouttonApproActionPerformed

    private void jComboBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseExited
        // TODO add your handling code here:
         
            
    }//GEN-LAST:event_jComboBox2MouseExited

    private void bEnregistrerVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEnregistrerVenteMouseClicked
        // TODO add your handling code here:
         DateFormat fd = new SimpleDateFormat("yyyy-MM-dd"); 
        java.util.Date aujourdhui = Calendar.getInstance().getTime();
	String dateFormatee = fd.format(aujourdhui);
        String TypeMedoc;
         String dat=dateFormatee;
        TypeMedoc = comboTypeVente.getSelectedItem().toString();
	String NomMedoc = textLibelleVente.getText();
        int Quantite=0;
        try{
             Quantite = Integer.valueOf(textQuantiteVente.getText()); 
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "numéro invalide !");
        }
       
	int Prix =0;
        try{
            Prix=Integer.valueOf(textPrixVente.getText());
        }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(null, "numéro invalide !");
        }

  
        String requete="INSERT INTO Vente (idphar,typeMedoc,libelle,quantite,prix,datevente) VALUES('"+labelPseudo.getText()+"','"+TypeMedoc+"','"+NomMedoc+"','"+Quantite+"','"+Prix+"','"+dat+"')";
      
 
       Statement smt0,smt88,mnt1,smt,stat1,mnt;
        ResultSet rs0,rs88;
        int var = 0;
        String nom = textLibelleVente.getText ();  
       String quantite = textQuantiteVente.getText ();
      String identifiant = labelPseudo.getText ();
   
      String sql="select * from stock where idphar='"+identifiant+"' AND nom='"+nom+"' ";
      
      int newquant= 0;
     boolean ok=false;
   
     try{
           smt88=connexion.getConnexionFromDatabase().createStatement();
           rs88=smt88.executeQuery(sql);
            while(rs88.next()){
               var++;
               if(var==1){
                   ok=true;
                   newquant=Integer.valueOf(rs88.getString("quantite"))-Quantite;
                   if(newquant>=0){
                    try{
                        stmt=connexion.getConnexionFromDatabase().createStatement();
                        stmt.executeUpdate(requete);
                        JOptionPane.showMessageDialog(null,"Vente enregistrée avec succes");
                        panelVente.setVisible(false);
                         }                                        
                      catch(SQLException ex){
                         System.out.println(ex);
                     }
                    
                    String requete2 = "UPDATE stock SET quantite= '"+newquant+"' WHERE idphar='"+identifiant+"' AND nom='"+nom+"' ";
                    try
                      {
                        stat1=connexion.getConnexionFromDatabase().createStatement();
                        stat1.executeUpdate(requete2);
                      }
                      catch(SQLException ex) {
                           System.err.println(ex); 
                      }
                   }else{
                      JOptionPane.showMessageDialog(null,"Quantité insuffisante!");
 
                   }
                    break;
            }
            
            }
            
        }
        catch (Exception ex){
            System.err.println(ex);
            JOptionPane.showMessageDialog(null, "non");
        } 
        if (ok ==false) {
            JOptionPane.showMessageDialog(null,"Ce médicament n'est pas dans le stock!");
        }
      
    }//GEN-LAST:event_bEnregistrerVenteMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         Statement stmt;
    ResultSet rs ;
    connexionToDatabase connexion = new connexionToDatabase();
    PreparedStatement pst=null;
        panelStock.setVisible(true);
        panelVente.setVisible(false);
        panelAppro.setVisible(false);
        panelAccueil.setVisible(false);
         panelConsulterVente.setVisible(false);
         String identifiant = labelPseudo.getText ();  
          String typ = jComboBox1.getSelectedItem().toString();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(" type");
        model.addColumn(" nom");
        model.addColumn("prix");
        model.addColumn("Quantite");
        model.addColumn("date expiration");
      
         String sql="select * from stock where idphar='"+identifiant+"' and type='"+typ+"'";
         try
       {
         
        
         stmt=connexion.getConnexionFromDatabase().createStatement();
          ResultSet resultat = stmt.executeQuery(sql); 
            while (resultat.next()){
         model.addRow(new Object[]{resultat.getString("type"),resultat.getString("nom"),resultat.getString("prix"),resultat.getString("quantite"),resultat.getString("dateexpiration")});
             }
        }
       catch(SQLException ex) {
            System.err.println(ex);
           
       }
           jTable1.setModel(model);

    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaPharmacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaPharmacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulerAppro;
    private javax.swing.JButton bAnnulerVente;
    private javax.swing.JLabel bConnexion;
    private javax.swing.JButton bEnregistrerAppro;
    private javax.swing.JButton bEnregistrerVente;
    private javax.swing.JLabel bconn;
    private javax.swing.JLabel binscription;
    private javax.swing.JButton boutonOk;
    private javax.swing.JButton boutonOk1;
    private javax.swing.JButton bouttonAppro;
    private javax.swing.JButton bouttonParam;
    private javax.swing.JButton bouttonStat;
    private javax.swing.JButton bouttonStock;
    private javax.swing.JButton bouttonVente;
    private javax.swing.JButton btnReach;
    private javax.swing.JDesktopPane bureau;
    private javax.swing.JComboBox<String> comboTypeAppro;
    private javax.swing.JComboBox<String> comboTypeMedic;
    private javax.swing.JComboBox<String> comboTypeR;
    private javax.swing.JComboBox<String> comboTypeVente;
    private javax.swing.JLabel deconnexion;
    private javax.swing.JLabel entete;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelPseudo;
    private javax.swing.JLabel labelPwd;
    private javax.swing.JPanel panelAccueil;
    private javax.swing.JPanel panelAlerte;
    private javax.swing.JPanel panelAppro;
    private javax.swing.JPanel panelConnexion;
    private javax.swing.JPanel panelConsulterVente;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelVente;
    private javax.swing.JLabel reglage;
    private javax.swing.JTextField textLibelleAppro;
    private javax.swing.JTextField textLibelleVente;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textPrixAppro;
    private javax.swing.JTextField textPrixVente;
    private javax.swing.JTextField textPseudo;
    private javax.swing.JTextField textQuantiteAppro;
    private javax.swing.JTextField textQuantiteVente;
    private javax.swing.JTextField textRecherche;
    private javax.swing.JTextField textannee;
    private javax.swing.JTextField textreference;
    // End of variables declaration//GEN-END:variables
}
